version: 0.1-{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(appveyor_repo_commit)
before_build:
- ps: '[System.IO.File]::AppendAllText("C:\Windows\System32\drivers\etc\hosts", "`n93.184.221.200  api.nuget.org")'
- cmd: >-
    git submodule update --init --recursive

    nuget restore OWLeagueLib.sln
build:
  project: OWLeagueLib.sln
  verbosity: minimal
artifacts:
- path: OWLeagueLib\bin\Release\OWLeagueLib.dll
  name: OWLeagueLib.dll
cache:
  - packages -> **\packages.config 
